rbac:
 create: true
 rules:
 - apiGroups: [""]
   resources: ["pods", "secrets", "configmaps"]
   verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
 - apiGroups: [""]
   resources: ["pods/exec", "pods/attach"]
   verbs: ["create", "patch", "delete"]
 - apiGroups: [""]
   resources: ["pods/log"]
   verbs: ["get"]

runners:
  protected: true
  tags: "kaniko,kubernetes"
  config: |
    [[runners]]
      executor = "kubernetes"
      shell = "bash"
      
      [runners.kubernetes.node_selector]
        "node_pool" = "linux-pool"

      [runners.kubernetes]
        namespace = "sensitive"
        poll_interval = 30
        poll_timeout = 3600

        [[runners.kubernetes.volumes.secret]]
          name = "kaniko-secret"
          mount_path = "/secret"
          read_only = true