rbac:
 create: true
 rules:
 - apiGroups: [""]
   resources: ["pods", "secrets", "configmaps"]
   verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
 - apiGroups: [""]
   resources: ["pods/exec", "pods/attach"]
   verbs: ["create", "patch", "delete"]
 - apiGroups: [""]
   resources: ["pods/log"]
   verbs: ["get"]

runners:
  tags: "linux,kubernetes"
  config: |
    [[runners]]
      executor = "kubernetes"
      limit = 30
      shell = "bash"
      [runners.kubernetes.node_selector]
        "node_pool" = "linux-pool"

      [runners.kubernetes]
        namespace = "default"
        poll_interval = 30
        poll_timeout = 3600