# Gitlab Runner level hosts var
hostAliases:
 - ip: "10.0.0.2"
   hostnames:
    - "gitlab.local"
locked: "false"
logLevel: debug
tags: "windows,kubernetes"
rbac:
 create: true
 rules:
 - resources: ["pods", "secrets", "configmaps","pods/attach", "pods/exec"]
   verbs: ["*"]
  #  verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
runners:
  config: |
    [[runners]]
      name = "shell executor runner"
      executor = "kubernetes"
      builds_dir = "C:\\GitLab-Runner\\builds"
      cache_dir = "C:\\GitLab-Runner\\cache"
      shell  = "powershell"
      
      # The FF_USE_POWERSHELL_PATH_RESOLVER feature flag has to be enabled for PowerShell 
      # to resolve paths for Windows correctly when Runner is operating in a Linux environment
      # but targeting Windows nodes.
      environment = ["FF_USE_POWERSHELL_PATH_RESOLVER=1"]

      [runners.kubernetes.node_selector]
        "kubernetes.io/os" = "windows"
        "node.kubernetes.io/windows-build" = "10.0.17763"
        "kubernetes.io/arch" = "amd64"

      [runners.kubernetes]
        namespace = "default"
        poll_interval = 30
        poll_timeout = 3600