rbac:
 create: true
 rules:
 - apiGroups: [""]
   resources: ["pods", "secrets", "configmaps"]
   verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
 - apiGroups: [""]
   resources: ["pods/exec", "pods/attach"]
   verbs: ["create", "patch", "delete"]
 - apiGroups: [""]
   resources: ["pods/log"]
   verbs: ["get"]
   
runners:
  tags: "windows,kubernetes"
  config: |
    [[runners]]
      name = "shell executor runner"
      executor = "kubernetes"
      
      # The FF_USE_POWERSHELL_PATH_RESOLVER feature flag has to be enabled for PowerShell 
      # to resolve paths for Windows correctly when Runner is operating in a Linux environment
      # but targeting Windows nodes.
      environment = ["FF_USE_POWERSHELL_PATH_RESOLVER=1"]

      [runners.kubernetes.node_selector]
        "node_pool" = "windows-pool"   
    		"kubernetes.io/arch" = "amd64"
        "kubernetes.io/os" = "windows"
        "node.kubernetes.io/windows-build" = "10.0.17763"        


      [runners.kubernetes.node_tolerations]
        "node.kubernetes.io/os=windows" = "NoSchedule"

      [runners.kubernetes]
        namespace = "default"
        poll_interval = 30
        poll_timeout = 3600